### ISSUE TITLE
Format of a MediaSourceReference not working with float?

### ISSUE THREAD

**Issue by pietrop** [bbc/html5-video-compositor#9] opened 2016-01-14 03:05 UTC
in the MediaSourceReference used to instantiate the VideoCompositor, the fields `start`, `sourceStart` and `duration` seem to work with inters but not with float, this makes it difficult to do accurate cut programmatically. Was wondering it there's any ways a round that? or if it's possible to add support for float?

**Comment by MatthewShotton** [comment] 2016-01-14 10:44
Hi pietrop, you should be able to use floats in all of those fields currently. If it's not working it may be an issue with how the videos are encoded (the compositor is quite picky about this), how they're being served, or possibly the browser (at the moment things are working best in chrome). 

Internally the compositor uses setting of a video elements currentTime property to implements sourceStart & duration. So a quick test to see if things are behaving as expected could be to try programmatically setting the currentTime of the videos you're using and to see if that seeks to the expected point.

**Comment by pietrop** [comment] 2016-01-14 11:57
Hi Matthew, 
Thanks, I am using it in [nw js](http://nwjs.io) so an implementation of Chromium for desktop apps. 
However as it's tricky to enable mp4 there(due to licencing issues) I am converting the videos in `ogg` for now, and thought that could be the issue. 

But I run the test as you suggested with `currentTime` and it works fine
```javascript 
videoCompositor.currentTime = 10.04;
```

Then I tried playing a sequence modifying the example once with float, and that works as well 

```javascript 
  var playlist =  {
        "tracks":[
                    [
                      {type:"video", sourceStart:0.01, start:3.00, duration:2.01, src:"./media/Clip16.ogg", id:"1"},
                      {type:"video", sourceStart:20.01, start:5.02, duration:6.01, src:"./media/debate_test.ogg", id:"2"},
                       {type:"video", sourceStart:30.01, start:11.03, duration:6.01, src:"./media/debate_test.ogg", id:"3"}
                    ] 
                ]
      };

//testing the video compositor with float sequence

canvas = document.getElementById('player-canvas');
videoCompositor = new VideoCompositor(canvas);
videoCompositor.playlist = playlist;
videoCompositor.play();
```

Anyway, thanks I've now narrowed it down to a problem with the code I am using to generate the playlist programmatically. As I am getting this error `Uncaught MediaSourceReferences 3 in track 0 starts before previous MediaSourceReference`, which I am assuming it means the timing in the playlist are not right?

**Comment by MatthewShotton** [comment] 2016-01-14 13:55
Hi pietrop, yeah that error is thrown when the end of one MediaSourceReference overlaps with the start of another on the same track. JavaScript rounding errors could be the cause of the error, one potential solution is to round start, sourceStart, and duration times to the nearest integer number of frames (i.e round to nearest 0.04 seconds for 25 fps video).

**Comment by pietrop** [comment] 2016-01-14 14:54
sounds good, I am not sure how would I round `start`, `sourceStart`, and `duration`  to the nearest integer number of frames?  

at the moment I was using 

```javascript
parseFloat(numberToRoundUp).toFixed(2)
```

**Comment by MatthewShotton** [comment] 2016-01-14 15:16
Something like this maybe? Although you'd need to know the frame-rate of the video up front.
```
var result = (Math.round(numberToRound*25))/25;

```

**Comment by pietrop** [comment] 2016-01-14 15:33
cool, make sense, I'll try it out, 

yeah I guess you could have the fps as a variable

```javascript
// rounding time to the nearest integer number of frames
var fps = 25; 
var result = (Math.round(numberToRound*fps))/fps;
```

Thanks

**Comment by MatthewShotton** [comment] 2016-01-15 10:20
I'm going to close this issue for now as it appears the original problem is resolved.

**Closed by MatthewShotton** 2016-01-15 10:20 UTC

**Comment by pietrop** [comment] 2016-01-15 10:26
Sounds good, thanks!
